language: nix

# Do not spam me with build status emails.
notifications:
  email: false

cache:
  directories:
    - app/.psc-package
    - .stack-work

before_cache:
  # The Stack database changes even when no code changes, do not cache it.
  - rm $HOME/.stack/stack.sqlite3

before_install:
  # Bring all the tools from the pinned build environment into the PATH.
  - export devenv_path=$(nix-build --no-out-link)
  - export PATH=${devenv_path}/bin:$PATH
  - export LIBRARY_PATH=${devenv_path}/lib:$LIBRARY_PATH

  # Binaries in the profile built above may need locales, that they can't find
  # unless we point LOCALE_ARCHIVE at the archive that contains them.
  - export LOCALE_ARCHIVE=${devenv_path}/lib/locale/locale-archive

script:
  - stack build --no-terminal
  - make -C app
