[[species]]
# Actual name is "Dypsis lutescens" according to Wikipedia, but it is called
# "Areca" everywhere, with nicknames "golden cane palm" and "butterfly palm".
# Source: https://www.123planten.nl/verzorging/tips-areca
# Source: https://www.groenrijk.nl/tuintips/111/areca-palm-verzorging
name = "Areca flavescens"
aliases = ["Golden cane palm", "Butterfly palm"]
water_days_summer = 3
water_days_winter = 7
water_remark =
  """\
  Keep the soil moist, also in winter. \
  Watering a little often, is better than a lot infrequently. \
  Sprinkle often, daily during winter if the air is dry.\
  """
# Once source says add fertilizer in summer every time you water, the other
# source says add fertilizer every 14 days. I'll go with the lazy option.
fertilize_days_summer = 14
fertilize_days_winter = 180
fertilize_remark = "Don’t fertilize in winter."
light = "Bright, no direct sunlight"

[[species]]
name = "Aglaonema Silver Bay"
# Source https://www.123planten.nl/aglaonema-silver-bay-agsba24070.html
water_days_summer = 4
water_days_winter = 10
water_remark =
  """\
  Keep the soil slightly moist. \
  In winter, it is okay if the soil dries out in between watering. \
  The plant is not demanding, \
  prefer to water too little over too much. \
  Sprinkling is not necessary but can be beneficial.\
  """
fertilize_days_summer = 30
fertilize_days_winter = 30
fertilize_remark =
  """\
  Requires little fertilizer. \
  Too much fertilizer can turn the soil acid, \
  which harms the plant.\
  """
light = "Bright, but at most three hours of direct sunlight"

[[species]]
name = "Chlorophytum comosum"
water_days = 6 # TODO: Source good value.
fertilize_days = 14 # TODO: Source good value.
# Source: https://www.rhs.org.uk/Plants/67933/i-Chlorophytum-comosum-i-Vittatum-(v)/Details
light = "Partial shade"
remarks = "When the leaves turn pale, the plant needs water."

[[species]]
name = "Dieffenbachia seguine"
# Source: https://www.intratuin.nl/dieffenbachia-dieffenbachia-seguine-tropic-snow-d-21-h-85-cm.html
# Says water once a week, but mine seems to need more, so let's dial it down to
# every 5 days. All sources say it needs lots of water and moist soil. Wikipedia
# says water "about twice a week". It also says both "moderately moist" and
# "moderately dry" two sentences apart, so not sure how trustworthy the data is.
water_days = 5
# Source: https://www.rhs.org.uk/Plants/96172/i-Dieffenbachia-i-Camille-(v)/Details
# Says "monthly".
fertilize_days = 30
light = "Half-shadow, no direct sunlight"

[[species]]
name = "Echeveria"
water_days = 10
fertilize_days = 365
light = "Sunny"

[[species]]
name = "Hedera Helix"
water_days = 6 # TODO: Source good value.
fertilize_days = 14 # TODO: Source good value.
light = "TODO"

[[species]]
name = "Sansevieria trifasciata"
# Source: https://www.houseofplants.co.uk/plants/sansevieria-trifasciata-laurentii_mother-in-laws-tongue_87403.html
# Source: https://www.houseplantsexpert.com/mother-in-laws-tongue.html
# During the winter only once a month, according to second source. First source
# says only "when soil is dry".
water_days = 14
# The first source says once every two months in spring-summer. The second
# source says once every month spring-fall. Take the middle ground.
fertilize_days = 45
light = "Indifferent, from full sun to shade"
remarks = "Don't water too much, ensure the soil is dry before watering. Water even less in winter."

[[species]]
name = "Sempervivum"
water_days = 10
fertilize_days = 365
light = "Sunny"
