[[species]]
name = "Chlorophytum comosum"
water_days = 6 # TODO: Source good value.
fertilize_days = 14 # TODO: Source good value.
# Source: https://www.rhs.org.uk/Plants/67933/i-Chlorophytum-comosum-i-Vittatum-(v)/Details
light = "Partial shade"
remarks = "When the leaves turn pale, the plant needs water."

[[species]]
name = "Dieffenbachia seguine"
# Source: https://www.intratuin.nl/dieffenbachia-dieffenbachia-seguine-tropic-snow-d-21-h-85-cm.html
# Says water once a week, but mine seems to need more, so let's dial it down to
# every 5 days. All sources say it needs lots of water and moist soil. Wikipedia
# says water "about twice a week". It also says both "moderately moist" and
# "moderately dry" two sentences apart, so not sure how trustworthy the data is.
water_days = 5
# Source: https://www.rhs.org.uk/Plants/96172/i-Dieffenbachia-i-Camille-(v)/Details
# Says "monthly".
fertilize_days = 30
light = "Half-shadow, no direct sunlight"

[[species]]
name = "Echeveria"
water_days = 10
fertilize_days = 365
light = "Sunny"

[[species]]
name = "Hedera Helix"
water_days = 6 # TODO: Source good value.
fertilize_days = 14 # TODO: Source good value.
light = "TODO"

[[species]]
name = "Sansevieria trifasciata"
# Source: https://www.houseofplants.co.uk/plants/sansevieria-trifasciata-laurentii_mother-in-laws-tongue_87403.html
# Source: https://www.houseplantsexpert.com/mother-in-laws-tongue.html
# During the winter only once a month, according to second source. First source
# says only "when soil is dry".
water_days = 14
# The first source says once every two months in spring-summer. The second
# source says once every month spring-fall. Take the middle ground.
fertilize_days = 45
light = "Indifferent, from full sun to shade"
remarks = "Don't water too much, ensure the soil is dry before watering. Water even less in winter."

[[species]]
name = "Sempervivum"
water_days = 10
fertilize_days = 365
light = "Sunny"
