[[species]]
name = "Aglaonema Silver Bay"
# Source https://www.123planten.nl/aglaonema-silver-bay-agsba24070.html
water_days_summer = 5
water_days_winter = 9
water_remark =
  """\
  Keep the soil slightly moist. \
  In winter, it is okay if the soil dries out in between watering. \
  The plant is not demanding, \
  prefer to water too little over too much. \
  Misting is not necessary but can be beneficial.\
  """
fertilize_days_summer = 30
fertilize_days_winter = 30
fertilize_remark =
  """\
  Requires little fertilizer. \
  Too much fertilizer can turn the soil acid, \
  which harms the plant.\
  """
light = "Bright, but at most three hours of direct sunlight"

[[species]]
name = "Areca flavescens"
# Actual name is "Dypsis lutescens" according to Wikipedia, but it is called
# "Areca" everywhere, with nicknames "golden cane palm" and "butterfly palm".
# Source: https://www.123planten.nl/verzorging/tips-areca
# Source: https://www.groenrijk.nl/tuintips/111/areca-palm-verzorging
aliases = ["Golden cane palm", "Butterfly palm"]
water_days_summer = 3
water_days_winter = 7
water_remark =
  """\
  Keep the soil moist, also in winter. \
  Watering a little often, is better than a lot infrequently. \
  Mist often, daily during winter if the air is dry.\
  """
# Once source says add fertilizer in summer every time you water, the other
# source says add fertilizer every 14 days. I'll go with the lazy option.
fertilize_days_summer = 14
fertilize_days_winter = 180
fertilize_remark = "Don’t fertilize in winter."
light = "Bright, no direct sunlight"

[[species]]
name = "Calathea orbifolia"
# Source: https://www.123planten.nl/verzorging/tips-calathea
water_days_summer = 3
water_days_winter = 6
water_remark =
  """\
  Keep the soil moist, water when it starts to dry. \
  Hanging and curling leaves are a sign of too little water. \
  Watering a little often, is better than a lot infrequently. \
  Misting is beneficial, especially in winter if the air is dry. \
  The edges of the leaves turn brown when misting too little.\
  """
fertilize_days_summer = 14
fertilize_days_winter = 180
fertilize_remark = "Don’t fertilize in winter."
light = "Shade or partial shade, no direct sunlight"

[[species]]
name = "Chlorophytum comosum"
# Source: https://www.rhs.org.uk/Plants/67933/i-Chlorophytum-comosum-i-Vittatum-(v)/Details
# https://www.plantsome.nl/products/graslelie-chlorophytum
water_days_summer = 4
water_days_winter = 4
water_remark =
  """\
  Keep the soil slightly moist. \
  When the leaves turn pale, the plant needs water. \
  Mist weekly.\
  """
fertilize_days_summer = 30
fertilize_days_winter = 180
fertilize_remark = "Needs fertilizer during the summer months."
light = "Bright to partial shade, no direct sunlight"

[[species]]
name = "Coffea arabica"
# Source: https://www.123planten.nl/verzorging/tips-coffea-arabica.
water_days_summer = 5
water_days_winter = 7
water_remark =
  """\
  Keep the soil slightly to moderately moist. \
  Misting regularly to keep humidity high and the leaves clean.\
  """
fertilize_days_summer = 14
fertilize_days_winter = 180
fertilize_remark = "Don’t fertilize in winter."
light = "Sunny, at least five hours of direct sunlight"

[[species]]
name = "Ctenanthe burle-marxii"
# Source: https://pistilsnursery.com/products/ctenanthe-burle-marxii-fishbone-prayer-plant
# Source: https://www.plantsome.nl/products/ctenanthe-burle-marxii
# Source: https://fair-flora.com/en/our-growers/vde-plant/ctenanthe-burle-marxii/
water_days_summer = 7
water_days_winter = 14
water_remark =
  """\
  Keep the soil slightly moist, do not allow the soil to dry out entirely. \
  Mist periodically.\
  """
fertilize_days_summer = 14
fertilize_days_winter = 180
fertilize_remark = "Needs very little fertilizer."
light = "From bright to shade; no direct sunlight"

[[species]]
name = "Dieffenbachia seguine"
# Source: https://www.intratuin.nl/dieffenbachia-dieffenbachia-seguine-tropic-snow-d-21-h-85-cm.html
# Source: https://plantingman.com/dumb-cane-dieffenbachia-summer-style-indoor-house-plants/
# Source: https://www.rhs.org.uk/Plants/96172/i-Dieffenbachia-i-Camille-(v)/Details
water_days_summer = 4
water_days_winter = 6
water_remark =
  """\
  Keep the soil evenly moist, but not soggy. \
  It is okay for the top soil to become a bit dry between each watering. \
  Water less often in winter. \
  """
fertilize_days_summer = 14
fertilize_days_winter = 60
fertilize_remark =
  """\
  Fertilize every two weeks in summer, every month in spring and fall. \
  Don’t fertilize in winter.\
  """
light = "Bright to partial shade, no direct sunlight (sunlight burns the leaves)"

[[species]]
name = "Echeveria"
# Source: https://www.intratuin.nl/echeveria-echeveria-pilosa-d-14-h-27-cm.html
# Source: https://www.succulentsandsunshine.com/types-of-succulents/echeveria-violet-queen/
# Source: https://www.drought-smart-plants.com/how-to-grow-echeveria.html
water_days_summer = 12
water_days_winter = 14
water_remark =
  """\
  Soak the soil, then let it dry out completely. \
  Avoid letting water sit on the leaves for too long \
  to prevent rot and fungus. \
  Rainwater works well because it is low on minerals. \
  The plant stores water in its leaves, so it needs very little water.\
  """
fertilize_days_summer = 60
fertilize_days_winter = 90
fertilize_remark =
  """\
  Rarely needs fertilizer. \
  Add a little bit of diluted liquid fertilizer if the plant appears pale.\
  """
light = "Sunny"

# [[species]]
# name = "Hedera Helix"
# water_days = 6 # TODO: Source good value.
# fertilize_days = 14 # TODO: Source good value.
# light = "TODO"

[[species]]
name = "Phlebodium areum"
# Source: https://www.123planten.nl/verzorging/tips-phlebodium
water_days_summer = 3
water_days_winter = 6
water_remark =
  """\
  Keep the soil slightly moist at all times. \
  Prefer to water at the edges of the pot. \
  Mist regularly.\
  """
fertilize_days_summer = 30
fertilize_days_winter = 90
fertilize_remark = "Needs very little fertilizer."
light = "Anything apart from direct sunlight is fine"

[[species]]
name = "Pilea peperomioides"
# Source: https://www.plantsome.nl/products/pannenkoekenplant-pilea-peperomioides-l
# Source: https://www.ourhouseplants.com/plants/pilea-peperomioides
water_days_summer = 7
water_days_winter = 7
water_remark =
  """\
  Water thoroughly and then let the soil dry out. \
  Needs less water in winter. \
  Mist regularly.\
  """
fertilize_days_summer = 30
fertilize_days_winter = 180
fertilize_remark = "Fertilize once a month in the growing season."
light = "Bright, can tolerate a little bit of direct sunlight"

[[species]]
name = "Sansevieria trifasciata"
# Source: https://www.123planten.nl/verzorging/tips-sansevieria
# Source: https://www.houseofplants.co.uk/plants/sansevieria-trifasciata-laurentii_mother-in-laws-tongue_87403.html
# Source: https://www.houseplantsexpert.com/mother-in-laws-tongue.html
water_days_summer = 14
water_days_winter = 35
water_remark =
  """\
  Needs very little water; don’t water when in doubt. \
  Let the soil dry out completely before watering again. \
  In summer, watering once every two weeks is sufficient. \
  In winter, the plant can easily survive for 6 to 8 weeks without watering. \
  Misting is unnecessary, but can help to remove dust.\
  """
# The first source says once every two months in spring-summer. The second
# source says once every month spring-fall. Take the middle ground.
fertilize_days_summer = 45
fertilize_days_winter = 180
fertilize_remark =
  """\
  Use little fertilizer, about 1/4 of an average liquid fertilizer dose.\
  """
light = "Indifferent, from full sun to shade"
