name = "Pilea peperomioides"
# Source: https://www.plantsome.nl/products/pannenkoekenplant-pilea-peperomioides-l
# Source: https://www.ourhouseplants.com/plants/pilea-peperomioides
water_days_summer = 7
water_days_winter = 7
water_remark =
  """\
  Water thoroughly and then let the soil dry out. \
  Needs less water in winter. \
  Mist regularly.\
  """
fertilize_days_summer = 30
fertilize_days_winter = 180
fertilize_remark = "Fertilize once a month in the growing season."
light = "Bright, can tolerate a little bit of direct sunlight"
