[[species]]
name = "Aglaonema Silver Bay"
# Source https://www.123planten.nl/aglaonema-silver-bay-agsba24070.html
water_days_summer = 5
water_days_winter = 9
water_remark =
  """\
  Keep the soil slightly moist. \
  In winter, it is okay if the soil dries out in between watering. \
  The plant is not demanding, \
  prefer to water too little over too much. \
  Misting is not necessary but can be beneficial.\
  """
fertilize_days_summer = 30
fertilize_days_winter = 30
fertilize_remark =
  """\
  Requires little fertilizer. \
  Too much fertilizer can turn the soil acid, \
  which harms the plant.\
  """
light = "Bright, but at most three hours of direct sunlight"

[[species]]
name = "Aloe vera"
# https://www.123planten.nl/verzorging/tips-aloe-vera
water_days_summer = 10
water_days_winter = 20
water_remark =
  """\
  Needs very little water, \
  just a bit to prevent the roots from drying out. \
  Can go without water for weeks in fall and winter. \
  When the tips of the leaves are contracting and turning red, \
  the plants needs more water. \
  With too much water, the leaves become soft and turn brown.\
  """
fertilize_days_summer = 90
fertilize_days_winter = 180
fertilize_remark =
  """\
  Requires very little fertilizer. \
  Fertilizer is most useful in spring. \
  Use cactus fertilizer, or 1/4 of a normal houseplant fertilizer dose.\
  """
light = "From direct sunlight to partial shade"

[[species]]
name = "Areca flavescens"
# Actual name is "Dypsis lutescens" according to Wikipedia, but it is called
# "Areca" everywhere, with nicknames "golden cane palm" and "butterfly palm".
# Source: https://www.123planten.nl/verzorging/tips-areca
# Source: https://www.groenrijk.nl/tuintips/111/areca-palm-verzorging
aliases = ["Golden cane palm", "Butterfly palm"]
water_days_summer = 3
water_days_winter = 7
water_remark =
  """\
  Keep the soil moist, also in winter. \
  Watering a little often, is better than a lot infrequently. \
  Mist often, daily during winter if the air is dry.\
  """
# Once source says add fertilizer in summer every time you water, the other
# source says add fertilizer every 14 days. I'll go with the lazy option.
fertilize_days_summer = 14
fertilize_days_winter = 180
fertilize_remark = "Don’t fertilize in winter."
light = "Bright, no direct sunlight"

[[species]]
name = "Cactus"
# Source: https://www.plantsome.nl/products/cactus-euphorbia-80cm?
# Source: https://www.123planten.nl/verzorging/tips-cactus
# Cactus is a member of the cactaceae family, not a species.
# The iconic cactus is actually an Euphorbia, not a cactus.
# But they need so little care that the details don't really matter.
aliases = ["Euphorbia"]
water_days_summer = 30
water_days_winter = 35
water_remark =
  """\
  Barely needs any water at all. \
  Prefer watering a lot once in a while, over watering a little frequently.\
  """
fertilize_days_summer = 120
fertilize_days_winter = 180
fertilize_remark =
  """\
  Requires very little fertilizer because it grows slowly. \
  Don’t fertilize in winter.\
  """
light = "Sunny"

[[species]]
name = "Calathea orbifolia"
# Source: https://www.123planten.nl/verzorging/tips-calathea
water_days_summer = 3
water_days_winter = 6
water_remark =
  """\
  Keep the soil moist, water when it starts to dry. \
  Hanging and curling leaves are a sign of too little water. \
  Watering a little often, is better than a lot infrequently. \
  Misting is beneficial, especially in winter if the air is dry. \
  The edges of the leaves turn brown when misting too little.\
  """
fertilize_days_summer = 14
fertilize_days_winter = 180
fertilize_remark = "Don’t fertilize in winter."
light = "Shade or partial shade, no direct sunlight"

[[species]]
name = "Chlorophytum comosum"
# Source: https://www.rhs.org.uk/Plants/67933/i-Chlorophytum-comosum-i-Vittatum-(v)/Details
# https://www.plantsome.nl/products/graslelie-chlorophytum
water_days_summer = 4
water_days_winter = 4
water_remark =
  """\
  Keep the soil slightly moist. \
  When the leaves turn pale, the plant needs water. \
  Mist weekly.\
  """
fertilize_days_summer = 30
fertilize_days_winter = 180
fertilize_remark = "Needs fertilizer during the summer months."
light = "Bright to partial shade, no direct sunlight"

[[species]]
name = "Coffea arabica"
# Source: https://www.123planten.nl/verzorging/tips-coffea-arabica.
water_days_summer = 5
water_days_winter = 7
water_remark =
  """\
  Keep the soil slightly to moderately moist. \
  Mist regularly to keep humidity high and the leaves clean.\
  """
fertilize_days_summer = 14
fertilize_days_winter = 180
fertilize_remark = "Don’t fertilize in winter."
light = "Sunny, at least five hours of direct sunlight"

[[species]]
name = "Ctenanthe burle-marxii"
# Source: https://pistilsnursery.com/products/ctenanthe-burle-marxii-fishbone-prayer-plant
# Source: https://www.plantsome.nl/products/ctenanthe-burle-marxii
# Source: https://fair-flora.com/en/our-growers/vde-plant/ctenanthe-burle-marxii/
water_days_summer = 7
water_days_winter = 14
water_remark =
  """\
  Keep the soil slightly moist, do not allow the soil to dry out entirely. \
  Mist periodically.\
  """
fertilize_days_summer = 14
fertilize_days_winter = 180
fertilize_remark = "Needs very little fertilizer."
light = "From bright to shade; no direct sunlight"

[[species]]
name = "Dieffenbachia seguine"
# Source: https://www.intratuin.nl/dieffenbachia-dieffenbachia-seguine-tropic-snow-d-21-h-85-cm.html
# Source: https://plantingman.com/dumb-cane-dieffenbachia-summer-style-indoor-house-plants/
# Source: https://www.rhs.org.uk/Plants/96172/i-Dieffenbachia-i-Camille-(v)/Details
water_days_summer = 4
water_days_winter = 6
water_remark =
  """\
  Keep the soil evenly moist, but not soggy. \
  It is okay for the top soil to become a bit dry between each watering. \
  Water less often in winter. \
  """
fertilize_days_summer = 14
fertilize_days_winter = 60
fertilize_remark =
  """\
  Fertilize every two weeks in summer, every month in spring and fall. \
  Don’t fertilize in winter.\
  """
light = "Bright to partial shade, no direct sunlight (sunlight burns the leaves)"

[[species]]
name = "Echeveria"
# Source: https://www.intratuin.nl/echeveria-echeveria-pilosa-d-14-h-27-cm.html
# Source: https://www.succulentsandsunshine.com/types-of-succulents/echeveria-violet-queen/
# Source: https://www.drought-smart-plants.com/how-to-grow-echeveria.html
water_days_summer = 12
water_days_winter = 14
water_remark =
  """\
  Soak the soil, then let it dry out completely. \
  Avoid letting water sit on the leaves for too long \
  to prevent rot and fungus. \
  Rainwater works well because it is low on minerals. \
  The plant stores water in its leaves, so it needs very little water.\
  """
fertilize_days_summer = 60
fertilize_days_winter = 90
fertilize_remark =
  """\
  Rarely needs fertilizer. \
  Add a little bit of diluted liquid fertilizer if the plant appears pale.\
  """
light = "Sunny"

[[species]]
name = "Ficus benjamina"
# Source: https://www.123planten.nl/verzorging/tips-ficus
# https://www.ikea.com/gb/en/p/ficus-benjamina-natasja-potted-plant-weeping-fig-56804613/
water_days_summer = 4
water_days_winter = 5
water_remark =
  """\
  Keep the soil slightly moist, without soaking the roots. \
  Watering a little often, is better than a lot infrequently. \
  Only water when the soil starts to feel dry. \
  Mist regularly, twice per week in winter if the air is dry.\
  """
fertilize_days_summer = 30
fertilize_days_winter = 180
fertilize_remark = """\
  Yellow leaves can be a sign of too little fertilizer. \
  Don’t fertilize in fall and winter. \
  Too much fertilizer can cause the soil to become acid.\
  """
# Some sources say no direct sunlight, 123planten says at least 5 hours of
# direct sunlight.
light = "At least 5 hours of direct sunlight"

[[species]]
name = "Hedera helix"
# Source: https://www.123planten.nl/verzorging/tips-hedera
water_days_summer = 5
water_days_winter = 5
water_remark =
  """\
  Keep the soil slightly moist at all times. \
  Watch out for water accumulating in the pot. \
  The plant losing its leaves, \
  and leaves with brown or yellow edges or spots, \
  are signs of too much water. \
  Misting is not necessary, but beneficial for removing dust and pests.\
  """
fertilize_days_summer = 21
fertilize_days_winter = 30
fertilize_remark =
  """\
  Fertilization is allowed, but not a necessity. \
  Too much fertilizer can cause the soil to become acid.\
  """
light = "Shade or half-shade"

[[species]]
name = "Monstera deliciosa"
# Not to be confused with Philendron.
# Source: https://www.rhs.org.uk/Plants/90394/i-Monstera-deliciosa-i-Variegata-(v)/Details
# Source: https://www.gardenista.com/posts/gardening-101-monstera-deliciosa-tropical-plant-guide/
# Source: https://greeneryunlimited.co/blogs/plant-care/monstera-deliciosa-care
# Also the label on the one I bought, which said water once per week and keep in
# half-shadow.
water_days_summer = 7
water_days_winter = 7
water_remark =
  """\
  The plant does not need a lot of water. \
  Let the top soil dry out before watering again. \
  Mist once a week.\
  """
fertilize_days_summer = 30
fertilize_days_winter = 180
fertilize_remark = "Fertilize monthly when in growth (spring and summer)."
light = "Partial shade, bright indirect light"

[[species]]
name = "Peperomia rotundifolia"
# Source: https://www.plantsome.nl/products/peperomia-rotundifolia-xs
# Source: https://www.intratuin.nl/peperomia-peperomia-rotundifolia-d-12-cm.html
# Source: https://www.houseplantsexpert.com/trailing-jade.html
water_days_summer = 7
water_days_winter = 7
water_remark =
  """\
  Allow the soil to become dry, then water thorougly. \
  Prefer to water too little over too much.\
  """
fertilize_days_summer = 30
fertilize_days_winter = 180
fertilize_remark =
  """\
  Fertilize every two weeks in spring with a diluted liquid fertilizer, \
  once a month in summer, \
  and don’t fertilize in fall and winter.\
  """
light = "Bright, without direct sunlight"

[[species]]
name = "Philodendron scandens"
# Source: https://www.123planten.nl/verzorging/tips-philodendron
# Source: https://www.guide-to-houseplants.com/heartleaf-philodendron.html
# Source: https://www.flowershopnetwork.com/blog/flower-plant-care/plant-care/heartleaf-philodendron-plant-care/
water_days_summer = 4
water_days_winter = 7
water_remark =
  """\
  Keep soil lightly moist, not soggy, in spring through fall. \
  In winter, allow the top soil to dry out in between waterings. \
  The plant needs little water, and is sensitive to overwatering. \
  Yellow or brown leaves indicate too much water. \
  The plant likes humid air, mist often, at least once a week.\
  """
fertilize_days_summer = 30
fertilize_days_winter = 180
fertilize_remark = "Fertilize spring through fall, don’t fertilize in winter."
light = "Partial shade, avoid direct sunlight"
light_remark =
  """\
  Small leaves, or long spaces between the leaves, \
  indicate that the plant is not getting enough light.\
  """

[[species]]
name = "Phlebodium areum"
# Source: https://www.123planten.nl/verzorging/tips-phlebodium
water_days_summer = 3
water_days_winter = 6
water_remark =
  """\
  Keep the soil slightly moist at all times. \
  Prefer to water at the edges of the pot. \
  Mist regularly.\
  """
fertilize_days_summer = 30
fertilize_days_winter = 90
fertilize_remark = "Needs very little fertilizer."
light = "Anything apart from direct sunlight is fine"

[[species]]
name = "Pilea peperomioides"
# Source: https://www.plantsome.nl/products/pannenkoekenplant-pilea-peperomioides-l
# Source: https://www.ourhouseplants.com/plants/pilea-peperomioides
water_days_summer = 7
water_days_winter = 7
water_remark =
  """\
  Water thoroughly and then let the soil dry out. \
  Needs less water in winter. \
  Mist regularly.\
  """
fertilize_days_summer = 30
fertilize_days_winter = 180
fertilize_remark = "Fertilize once a month in the growing season."
light = "Bright, can tolerate a little bit of direct sunlight"

[[species]]
name = "Rhaphidophora tetrasperma"
# Source: https://leafyplace.com/rhaphidophora-tetrasperma/
# Source: https://www.ohiotropics.com/2019/04/11/rhaphidophora-tetrasperma/
water_days_summer = 5
water_days_winter = 7
water_remark =
  """\
  Keep the soil moist, but not soggy. \
  Soak the soil, then water again when the top 2cm of the soil is dry. \
  Prefer watering too little over watering too much. \
  Yellow leaves are a sign of too much water. \
  Mist every two to three days.\
  """
fertilize_days_summer = 30
fertilize_days_winter = 90
fertilize_remark = "Only fertilize when the plant is growing."
light = "Bright indirect light, no direct sunlight"
light_remark =
  """\
  If the leaves of the plant do not split, \
  the plant needs more light.\
  """

[[species]]
name = "Sansevieria trifasciata"
# Source: https://www.123planten.nl/verzorging/tips-sansevieria
# Source: https://www.houseofplants.co.uk/plants/sansevieria-trifasciata-laurentii_mother-in-laws-tongue_87403.html
# Source: https://www.houseplantsexpert.com/mother-in-laws-tongue.html
water_days_summer = 14
water_days_winter = 35
water_remark =
  """\
  Needs very little water; don’t water when in doubt. \
  Let the soil dry out completely before watering again. \
  In summer, watering once every two weeks is sufficient. \
  In winter, the plant can easily survive for 6 to 8 weeks without watering. \
  Misting is unnecessary, but can help to remove dust.\
  """
# The first source says once every two months in spring-summer. The second
# source says once every month spring-fall. Take the middle ground.
fertilize_days_summer = 45
fertilize_days_winter = 180
fertilize_remark =
  """\
  Use little fertilizer, about 1/4 of an average liquid fertilizer dose.\
  """
light = "Indifferent, from full sun to shade"

[[species]]
name = "Scindapsus pictus"
# Source: https://www.123planten.nl/verzorging/tips-scindapsus
# Source: https://www.ohiotropics.com/2019/10/12/scindapsus-pictus-silver-philodendron/
water_days_summer = 4
water_days_winter = 6
water_remark =
  """\
  Keep the soil lightly moist, do not let it dry out. \
  Mist once in a while to remove dust.\
  """
fertilize_days_summer = 14
fertilize_days_winter = 180
fertilize_remark =
  """\
  Only fertilize when the plant is growing, \
  not in fall and winter.\
  """
light = "Bright to partial shade, no direct sunlight"
light_remark =
  """\
  A darker spot works too, the leaves will become darker, and greener. \
  The pattern in the leaves disappearing is a sign of too little light.\
  """

[[species]]
name = "Tillandsia"
# Source: https://www.plantsome.nl/products/tillandsia-in-schelp-i
# https://www.airplantcity.com/pages/air-plant-care
# One source says "mist every once in a while", the other says 2-3 times a week.
# I haven’t misted mine for two weeks and it is doing fine, so let's say 14
# days.
water_days_summer = 14
water_days_winter = 14
water_remark =
  """\
  Does not need to be watered, \
  but mist every once in a while for humidity.\
  """
fertilize_days_summer = 365
fertilize_days_winter = 365
# One source says it gets everything from the air, the other says there is
# special fertilizer. But normal liquid fertilizer is not going to work in any
# case.
fertilize_remark = "Does not need fertilization."
light = "Bright, no direct sunlight"
