name: "Build"

on: "push"

jobs:
  build:
    runs-on: "ubuntu-18.04"
    steps:
      - uses: "actions/checkout@v2"

      - uses: "cachix/install-nix-action@v10"
        with:
          nix_path: "nixpkgs=channel:nixos-unstable"

      - name: "Build"
        run: "nix run -c make"
