name: "Deploy"

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: "ubuntu-18.04"
    steps:
      - uses: "actions/checkout@v2"

      - uses: "cachix/install-nix-action@v10"
        with:
          nix_path: "nixpkgs=channel:nixos-unstable"

      - name: "Build"
        run: "nix run -c make"

      - name: "Deploy"
        uses: "peaceiris/actions-gh-pages@v3.6.1"
        with:
          github_token: "${{ secrets.GITHUB_TOKEN }}"
          commit_message: "${{ github.GITHUB_REF }}"
          publish_dir: "out"
